config/routes.rb
Rails.application.routes.draw do
  get 'manager_view_profile/index'
  get 'employee_view_profile/index'
  get 'guest_flavor_store/index'
  get 'guest_flavor_view/index'
  resources :loginpages
  resources :store_flavors
  resources :controllers
  get 'manager_shift_info/index'
  get 'employee_page/index'
  get 'manager_page/index'
  get 'admin_page/index'
  resources :shift_jobs
  resources :users
  resources :jobs
  resources :shifts
  resources :flavors
  resources :demos, only: [:new, :create, :destroy]
  get 'demos/new', to: 'loginpages#index', as: :login
  get 'demos/destroy', to: 'demos#destroy', as: :logout
  get 'page/mainpage'
  get 'admin_page/index'
  get 'manager_page/index'
  get 'manager_shift_info/index'
  get 'manager_assignment_info/index'
  get 'employee_page/index'
  resources :stores
  resources :employees
  resources :assignments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'demos#new'
end

app/models/employee.rb
class Employee < ApplicationRecord
 # Callbacks
  before_save :reformat_phone
  before_validation :reformat_ssn
  
  # Relationships
  has_many :assignments
  has_many :stores, through: :assignments
  has_many :shifts, through: :assignments
  has_one :user, dependent: :destroy
  accepts_nested_attributes_for :user
  
  # Validations
  validates_presence_of :first_name, :last_name, :date_of_birth, :ssn, :role
  validates_date :date_of_birth, on_or_before: lambda { 14.years.ago }, on_or_before_message: "must be at least 14 years old"
  validates_format_of :phone, with: /\A\(?\d{3}\)?[-. ]?\d{3}[-.]?\d{4}\z/, message: "should be 10 digits (area code needed) and delimited with dashes only", allow_blank: true
  validates_format_of :ssn, with: /\A\d{3}[- ]?\d{2}[- ]?\d{4}\z/, message: "should be 9 digits and delimited with dashes only"
  validates_inclusion_of :role, in: %w[admin manager employee], message: "is not an option"
  validates_uniqueness_of :ssn
  
  # Scopes
  scope :younger_than_18, -> { where('date_of_birth > ?', 18.years.ago.to_date) }
  scope :is_18_or_older,  -> { where('date_of_birth <= ?', 18.years.ago.to_date) }
  scope :active,          -> { where(active: true) }
  scope :inactive,        -> { where(active: false) }
  scope :regulars,        -> { where(role: 'employee') }
  scope :managers,        -> { where(role: 'manager') }
  scope :admins,          -> { where(role: 'admin') }
  scope :alphabetical,    -> { order('last_name, first_name') }
  
  # Other methods
  def name
    "#{last_name}, #{first_name}"
  end
  
  def proper_name
    "#{first_name} #{last_name}"
  end
  
  def current_assignment
    curr_assignment = self.assignments.select{|a| a.end_date.nil?}
    # alternative method for finding current assignment is to use scope 'current' in assignments:
    # curr_assignment = self.assignments.current    # will also return an array of current assignments
    return nil if curr_assignment.empty?
    curr_assignment.first   # return as a single object, not an array
  end
  
  def over_18?
    date_of_birth < 18.years.ago.to_date
  end
  
  def age
    (Time.now.to_s(:number).to_i - date_of_birth.to_time.to_s(:number).to_i)/10e9.to_i
  end
  
  # Misc Constants
  ROLES_LIST = [['Employee', 'employee'],['Manager', 'manager'],['Administrator', 'admin']]
  
  before_destroy :check_destroy_status
  after_rollback :make_inactive, :terminate_assignment, :delete_future_shifts
  #after_destroy :delete_assignment
  
  
  
  def check_destroy_status
    if worked_shift?
      #do something, cannot delete 
      self.errors.add(:base, 'cannot delete this employee')
      throw(:abort)
    else
      #delete 
      self.delete_assignment
    end
  end 
  
  def worked_shift?
    shifts = Shift.for_employee(self.id)
    shifts.to_a.size > 0
  end
  
   #private
   def reformat_phone
     phone = self.phone.to_s  # change to string in case input as all numbers 
     phone.gsub!(/[^0-9]/,"") # strip all non-digits
     self.phone = phone       # reset self.phone to new string
   end
   def reformat_ssn
     ssn = self.ssn.to_s      # change to string in case input as all numbers 
     ssn.gsub!(/[^0-9]/,"")   # strip all non-digits
     self.ssn = ssn           # reset self.ssn to new string
   end
   
   def delete_assignment
    assignment = self.assignments.current.first
    if !assignment.nil?
      self.assignments.current.first.delete
    end
   end
   
   def make_inactive 
    self.update_attribute(:active, false) if self.valid?
   end
   
   def terminate_assignment
    assignment = self.assignments.current.first
    if !assignment.nil?
      assignment.update_attribute(:end_date, Date.today)
    end
   end
   
   def delete_future_shifts
    Shift.for_employee(self.id).upcoming.each do |shift|
        shift.delete
    end
   end
end
   

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all.paginate(:page => params[:page]).per_page(10)
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    @employee.build_user
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :ssn, :date_of_birth, :phone, :role, :active, user_attributes: [:id, :email, :password])
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<div class= "container">
  <div class="row">
    <div class="col s12 center">
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if session[:role] != 'admin'  %>
  <% end  %>

  <div class="input-field">
    <%= form.label :first_name, class: "active" %>
    <%= form.text_field :first_name %>
  </div>

  <div class="input-field">
    <%= form.label :last_name, class: "active" %>
    <%= form.text_field :last_name %>
  </div>

  <div class="input-field">
    <%= form.label :ssn, class: "active" %>
    <% if session[:role] != 'admin'  %>
      <%= form.text_field :ssn, disabled: true %>
    <% else  %>
      <%= form.text_field :ssn %>
    <% end  %>
  </div>

  <div class="input-field">
    <%= form.label :date_of_birth, class: "active" %>
    <%= form.text_field :date_of_birth, prompt: "Date of Birth", class: "datepicker", :value =>(form.object.date_of_birth.strftime('%B %d, %Y') if form.object.date_of_birth != nil)%>
  </div>

  <div class="input-field">
    <%= form.label :phone, class: "active" %>
    <%= form.text_field :phone %>
  </div>
  
  <%= form.fields_for :user do |field|%>
    <div class="input-field">
    <%= field.label "Email", class: "active" %>
    <%= field.text_field :email %>
    </div>
    
    <div class="input-field">
    <%= field.label "Password" %>
    <%= field.password_field :password %>
    </div>
  <% end %>

  <div class="input-field">
    <%= form.label :role, class: "active" %>
    <%= form.select :role, %w[employee manager admin], :prompt => "Select..." %>
  </div>

  <div class="input-field">
    <%= form.label :active, class: "active" %>
    <%= form.select :active, options_for_select([['active', true], ['not active', false]]), :prompt => "Select One" %>
  </div>

  <div class="actions">
    <%= form.submit :class=>"btn waves-effect waves-light center" %>
    <% if session[:role] == 'employee'  %>
      <%= link_to 'Cancel', employee_page_index_path, :class => 'waves-effect waves-light btn red center' %>
    <% else  %>
      <%= link_to 'Cancel', employees_path, :class => 'waves-effect waves-light btn red center' %>
    <% end %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/employees/edit.html.erb
<h1 class="center">Editing Employee</h1>

<%= render 'form', employee: @employee %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col s12 center">
    

<h1>Employees</h1>

<!--Find all the employees that work at the same store as the manager-->
<% user = User.find(session[:user_id]) %>    
<% manager = Employee.find(user.employee.id) %>
<% manager_assignments = Assignment.for_employee(manager) %>
<% manager_stores = Array.new  %>
<% manager_assignments.each do |assignment| %>
    <% manager_stores << Store.find(assignment.store_id) %>
<% end %>
<% assignments_store = Array.new %>
<% manager_stores.each do |store| %>
    <% assignments_store << Assignment.for_store(store) %>
<% end %>
<% employees_all = Array.new %>
<% assignments_store.each do |assignment_relation| %>
    <% assignment_relation.each do |assignment| %>
        <% puts "Assignment_id:"%>
        <% puts "#{assignment.id}"  %>
        <% employees_all << Employee.find(assignment.employee_id) %>
    <% end %>
<% end %>    
<% employees_regulars = Array.new %>
<% employees_all.each do |employee| %>
    <% if employee.role == 'employee' %>
        <% employees_regulars << employee %>
    <% end %>
<% end %>

<table class="striped">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Ssn</th>
      <th>Date of birth</th>
      <th>Phone</th>
      <th>Role</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if session[:role] == 'manager' %>
    <% else %>
      <% employees_regulars = Employee.all %>
    <% end %>
    
    <% employees_regulars.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.ssn %></td>
        <td><%= employee.date_of_birth %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.role %></td>
        <td><%= employee.active %></td>
        <% if session[:role] == 'admin' %>
          <td><%= link_to 'Show', employee, :class=> "waves-effect waves-light btn green" %></td>
          <td><%= link_to 'Edit', edit_employee_path(employee), :class=> "waves-effect waves-light btn light-blue" %></td>
          <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "waves-effect waves-light btn red" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>


<% if session[:role] == 'admin' %> 
<%= link_to 'New Employee', new_employee_path, :class=> "waves-effect waves-light btn teal center" %>
<br/><br/>
<% end %>
<!-- Add the pagination using will_paginate gem -->
<span class="paginate">
<%= will_paginate @employees, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

<br>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<h1 class="center">New Employee</h1>

<%= render 'form', employee: @employee %>

app/views/employees/show.html.erb
      <div class="container center">
      <h1 class="center"><%= @employee.first_name + " " + @employee.last_name %></h1>
      
      <table class="highlight">
        <tr>
          <th class="center">SSN:</th>
          <td class="center"><%= @employee.ssn %></td>
        </tr>
        <tr>
          <th class="center">Phone: </th>
          <td class="center"><%= @employee.phone %></td>
        </tr>
        <tr>
          <th class="center">Date of Birth: </th>
          <td class="center"><%= @employee.date_of_birth %></td>
        </tr>
        <tr>
          <th class="center">Role: </th>
          <td class="center"><%= @employee.role %></td>
        </tr>
        <tr>
          <th class="center">Active: </th>
          <td class="center"><%= if @employee.active then "Active" else "Not Active" end %></td>
        </tr>
      </table>
<br/>
<%= link_to 'Edit', edit_employee_path(@employee), :class=>"btn waves-effect waves-light btn blue" %> |
<% if session[:role] == 'employee'  %>
  <%= link_to 'Back', employee_page_index_path, :class => 'waves-effect waves-light btn red' %>
<% else  %>
   <%= link_to 'Back', employees_path, :class => 'waves-effect waves-light btn red' %>
<% end %>
</div>
<br/><br/>