config/routes.rb
Rails.application.routes.draw do
  get 'manager_view_profile/index'
  get 'employee_view_profile/index'
  get 'guest_flavor_store/index'
  get 'guest_flavor_view/index'
  resources :loginpages
  resources :store_flavors
  resources :controllers
  get 'manager_shift_info/index'
  get 'employee_page/index'
  get 'manager_page/index'
  get 'admin_page/index'
  resources :shift_jobs
  resources :users
  resources :jobs
  resources :shifts
  resources :flavors
  resources :demos, only: [:new, :create, :destroy]
  get 'demos/new', to: 'loginpages#index', as: :login
  get 'demos/destroy', to: 'demos#destroy', as: :logout
  get 'page/mainpage'
  get 'admin_page/index'
  get 'manager_page/index'
  get 'manager_shift_info/index'
  get 'manager_assignment_info/index'
  get 'employee_page/index'
  resources :stores
  resources :employees
  resources :assignments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'demos#new'
end

app/models/flavor.rb
class Flavor < ApplicationRecord
  has_many :store_flavors
  has_many :stores, through: :store_flavors

  validates_presence_of :name

  scope :active,          -> { where(active: true) }
  scope :inactive,        -> { where(active: false) }
  scope :alphabetical,    -> { order('name') }
  
  before_destroy :cancel_destroy
  after_rollback :make_inactive
  
  def cancel_destroy
    self.errors.add(:base, 'cannot delete a flavor')
    throw(:abort)
  end
  
  def make_inactive
  	self.active = false
  	self.save
  end
  
end

app/controllers/flavors_controller.rb
class FlavorsController < ApplicationController
  before_action :set_flavor, only: [:show, :edit, :update, :destroy]

  # GET /flavors
  # GET /flavors.json
  def index
    @flavors = Flavor.all
  end

  # GET /flavors/1
  # GET /flavors/1.json
  def show
  end

  # GET /flavors/new
  def new
    @flavor = Flavor.new
  end

  # GET /flavors/1/edit
  def edit
  end

  # POST /flavors
  # POST /flavors.json
  def create
    @flavor = Flavor.new(flavor_params)

    respond_to do |format|
      if @flavor.save
        format.html { redirect_to @flavor, notice: 'Flavor was successfully created.' }
        format.json { render :show, status: :created, location: @flavor }
      else
        format.html { render :new }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flavors/1
  # PATCH/PUT /flavors/1.json
  def update
    respond_to do |format|
      if @flavor.update(flavor_params)
        format.html { redirect_to @flavor, notice: 'Flavor was successfully updated.' }
        format.json { render :show, status: :ok, location: @flavor }
      else
        format.html { render :edit }
        format.json { render json: @flavor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flavors/1
  # DELETE /flavors/1.json
  def destroy
    
    if @flavor.destroy
      respond_to do |format|
        format.html { redirect_to flavors_url, notice: 'Flavor was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to flavors_url, alert: " #{@flavor.errors[:base]}"}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flavor
      @flavor = Flavor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flavor_params
      params.require(:flavor).permit(:name, :active)
    end
end

app/helpers/flavors_helper.rb
module FlavorsHelper
end

app/views/flavors/_form.html.erb
<div class= "container">
<%= simple_form_for(@flavor) do |f| %>
  <% if flavor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flavor.errors.count, "error") %> prohibited this flavor from being saved:</h2>

      <ul>
      <% flavor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
  <div class="input-field">
    <%= f.label :name, class: "active" %>
    <%= f.text_field :name %>
  </div>
  <div class="input-field">
    <%= f.label :active, class: "active" %>
    <%= f.select :active, options_for_select([['active', true], ['not active', false]]), :prompt => "Select One" %>
  </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
</div>

app/views/flavors/edit.html.erb
<div class="center">
<h1>Editing Flavor</h1>

<%= render 'form', flavor: @flavor %>

<%= link_to 'Back', flavors_path, :class=> "waves-effect waves-light btn red center" %>
</div>

app/views/flavors/index.html.erb
<div class="container center">
<p id="notice"><%= notice %></p>

<h1>Flavors</h1>

<div class="container">

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flavors.each do |flavor| %>
      <tr>
        <td><%= flavor.name %></td>
        <td><%= flavor.active %></td>
        <% if session[:role]  %>
          <% if session[:role] == 'admin' %>
            <td><%= link_to 'Show', flavor, :class=> "waves-effect waves-light btn green" %></td>
            <td><%= link_to 'Edit', edit_flavor_path(flavor), :class=> "waves-effect waves-light btn light-blue" %></td>
            <td><%= link_to 'Destroy', flavor, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "waves-effect waves-light btn red" %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
<br>
<% if session[:role]  %>
  <% if session[:role] == 'admin' %>
    <%= link_to 'New Flavor', new_flavor_path, :class=> "waves-effect waves-light btn teal center" %>
  <% end %>
<% end %>
</div>

app/views/flavors/new.html.erb
<div class="center">
<h1>New Flavor</h1>

<%= render 'form', flavor: @flavor %>

<%= link_to 'Back', flavors_path, :class=> "waves-effect waves-light btn red center" %>
</div>

app/views/flavors/show.html.erb
<div class="container center">
<p id="notice"><%= notice %></p>
<h2>Flavor Details</h2>

<p>
  <strong>Name:</strong>
  <%= @flavor.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @flavor.active %>
</p>

<%= link_to 'Edit', edit_flavor_path(@flavor), :class=> "waves-effect waves-light btn light-blue" %> |
<%= link_to 'Back', flavors_path, :class=> "waves-effect waves-light btn red" %>
</div>